### ISSUE TITLE
Push, Index

### ISSUE THREAD

**Issue by Rillow** [Rillow/aula0903#2]
Ja dei meu primeiro Push, vou esperar as alterações de voces no arquivo. Se precisarem de ajuda me mandem uma mensagem.

**Comment by GabrielBazani** [comment]
:+1:

**Comment by GabrielBazani** [comment]
estamos tentando mudar o css mas não estamos conseguindo

**Comment by Rillow** [comment]
Voces estão utilizando os containers do CSS que voces instalaram?

**Comment by Rillow** [comment]
Qualquer coisa deem o push com o CSS errado mesmo, que eu tento corrigir

**Comment by GabrielBazani** [comment]
sim instalamos já vamos ver se a gente consegue aqui se não der eu mando errado pra você

**Comment by Rillow** [comment]
:+1:

**Comment by GabrielBazani** [comment]
nosso vs code travou e quando abre fica tela preta

**Comment by Rillow** [comment]
Meu Pai Celestial HAHAHAHAHAH

**Comment by GabrielBazani** [comment]
voltou ao normal agora reabrimos

**Comment by Rillow** [comment]
Eu vou apagar o pentagrama aqui então

**Comment by GabrielBazani** [comment]
mandei o push com o bootstrap ja

**Comment by Rillow** [comment]
:+1:
