### ISSUE TITLE
PHP e pasta

### ISSUE THREAD

**Issue by Rillow** [Rillow/aula0903#3]
Fizeram cagada aqui na pasta, mas o binho já acertou

**Comment by Rillow** [comment]
Vou dar commit e Push

**Comment by GabrielBazani** [comment]
kkkkk :+1:

**Comment by Rillow** [comment]
Dei  o Push

**Comment by GabrielBazani** [comment]
demos o pull

**Comment by GabrielBazani** [comment]
mas tem que ter no minio 5 commit o que podemos fazer ?

**Comment by GabrielBazani** [comment]
dei o push
