### ISSUE TITLE
Precisamos de dois Commits

### ISSUE THREAD

**Issue by Rillow** [Rillow/aula0903#4]
Tentem dar uma alterada no "Valor 1" e "Valor 2" e deem um commit, só pra nao ficar muito perdido

**Comment by Rillow** [comment]
só pra dar uma ajeitadinha no visual, com um <h2>Valor 1</h2> ou alguma coisa que voces acharem melhor, colocando um título na pagina

**Comment by GabrielBazani** [comment]
:+1:

**Comment by Rillow** [comment]
To dando uma ultima alterada no HTML

**Comment by GabrielBazani** [comment]
beleza

**Comment by Rillow** [comment]
Pode dar Pull, projetop finalizado :+1:

**Comment by GabrielBazani** [comment]
demos pull :+1:

**Comment by GabrielBazani** [comment]
Tudo pronto projeto bem sucedido!
